//app.js
App({
    //onLaunch,onShow: options(path,query,scene,shareTicket,referrerInfo(appId,extraData))
    globalData: {
        bookscateList: [{
                id: 1,
                name: '小说',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            },
            {
                id: 2,
                name: '学习',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            },
            {
                id: 3,
                name: '诗歌',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            },
            {
                id: 4,
                name: '说明文',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            },
            {
                id: 5,
                name: '悬疑',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            }
        ],
        plan: [{
                id: 1,
                name: '一年制普通会员',
                price: 100,
                days: 365,
                nums: 1,
                day: 7,
            },
            {
                id: 2,
                name: '两年制普通会员',
                price: 200,
                days: 730,
                nums: 1,
                day: 7,
            },
            {
                id: 3,
                name: '三年制普通会员',
                price: 300,
                days: 1095,
                nums: 1,
                day: 7,
            },
            {
                id: 4,
                name: '一年制超级会员',
                price: 200,
                days: 365,
                nums: 3,
                day: 14,
            },
            {
                id: 5,
                name: '两年制超级会员',
                price: 400,
                days: 730,
                nums: 3,
                day: 14,
            },
            {
                id: 6,
                name: '三年制超级会员',
                price: 600,
                days: 1095,
                nums: 3,
                day: 14,
            }
        ],
        customernum: 11,
        customerList: [{
                id: 8,
                phonenum: '18800416241',
                name: '徐洪磊',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-06-13',
                plan: 2,
                day: 1
            },
            {
                id: 13,
                phonenum: '18800416241',
                name: '小b',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-06-09',
                plan: 1,
                day: 0
            },
            {
                id: 12,
                phonenum: '18800416241',
                name: '小a',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 0,
                password: 111,
                birthday: '1999-06-05',
                plan: 1,
                day: 0
            },
            {
                id: 11,
                phonenum: '18800416241',
                name: '小小小智',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 0,
                password: 111,
                birthday: '1999-10-01',
                plan: 1,
                day: 0
            },
            {
                id: 10,
                phonenum: '18800416241',
                name: '小智',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-10-01',
                plan: 2,
                day: 1
            },
            {
                id: 9,
                phonenum: '18800416241',
                name: '小小智',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 0,
                password: 111,
                birthday: '1999-10-01',
                plan: 3,
                day: 0
            },
            {
                id: 14,
                phonenum: '18800416241',
                name: '大智',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-10-01',
                plan: 1,
                day: 0
            },
            {
                id: 7,
                phonenum: '18800416241',
                name: '大大智',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 0,
                password: 111,
                birthday: '1999-10-01',
                plan: 2,
                day: 0
            },
            {
                id: 6,
                phonenum: '18800416241',
                name: '大大大智',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-10-01',
                plan: 3,
                day: 1
            },
            {
                id: 1,
                phonenum: '18800416241',
                name: '曾智',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-10-01',
                plan: 1,
                day: 1
            },
            {
                id: 2,
                phonenum: '18800416241',
                name: '赵梓良',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 0,
                password: 111,
                birthday: '1999-10-01',
                plan: 1,
                day: 0
            },
            {
                id: 3,
                phonenum: '18800416241',
                name: '郑君烨',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-10-01',
                plan: 3,
                day: 0
            },
            {
                id: 4,
                phonenum: '18800416241',
                name: '高昊达',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-10-01',
                plan: 1,
                day: 1
            },
            {
                id: 5,
                phonenum: '18800416241',
                name: '王智义',
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
                gender: 1,
                password: 111,
                birthday: '1999-10-01',
                plan: 1,
                day: 1
            }
        ],
        sellstatus: [{
                id: 1,
                date: "2021-05-20",
                lr: 100,
                xse: 100,
                xscb: 50,
                qtsr: 100,
                qtzc: 50,
            },
            {
                id: 2,
                date: "2021-05-21",
                lr: 50,
                xse: 50,
                xscb: 50,
                qtsr: 100,
                qtzc: 50,
            },
            {
                id: 3,
                date: "2021-05-22",
                lr: 70,
                xse: 100,
                xscb: 30,
                qtsr: 50,
                qtzc: 50,
            },
            {
                id: 4,
                date: "2021-05-23",
                lr: 120,
                xse: 230,
                xscb: 310,
                qtsr: 410,
                qtzc: 210,
            },
            {
                id: 5,
                date: "2021-05-24",
                lr: 1000,
                xse: 4100,
                xscb: 2100,
                qtsr: 3100,
                qtzc: 4100,
            },
            {
                id: 6,
                date: "2021-05-25",
                lr: 280,
                xse: 510,
                xscb: 310,
                qtsr: 420,
                qtzc: 340,
            },
            {
                id: 7,
                date: "2021-05-26",
                lr: 290,
                xse: 530,
                xscb: 330,
                qtsr: 430,
                qtzc: 340,
            },
            {
                id: 8,
                date: "2021-05-27",
                lr: 100,
                xse: 100,
                xscb: 50,
                qtsr: 100,
                qtzc: 50,
            },
            {
                id: 9,
                date: "2021-05-28",
                lr: 290,
                xse: 530,
                xscb: 330,
                qtsr: 430,
                qtzc: 340,
            },
            {
                id: 10,
                date: "2021-05-29",
                lr: 1230,
                xse: 1500,
                xscb: 300,
                qtsr: 50,
                qtzc: 20,
            },
            {
                id: 11,
                date: "2021-05-30",
                lr: 290,
                xse: 530,
                xscb: 330,
                qtsr: 430,
                qtzc: 340,
            },
            {
                id: 12,
                date: "2021-05-31",
                lr: 100,
                xse: 100,
                xscb: 50,
                qtsr: 100,
                qtzc: 50,
            },
            {
                id: 13,
                date: "2021-06-01",
                lr: 290,
                xse: 530,
                xscb: 330,
                qtsr: 430,
                qtzc: 340,
            },
            {
                id: 14,
                date: "2021-06-02",
                lr: 1230,
                xse: 1500,
                xscb: 300,
                qtsr: 50,
                qtzc: 20,
            },
            {
                id: 15,
                date: "2021-06-03",
                lr: 280,
                xse: 510,
                xscb: 310,
                qtsr: 420,
                qtzc: 340,
            },
            {
                id: 16,
                date: "2021-06-04",
                lr: 1230,
                xse: 1500,
                xscb: 300,
                qtsr: 50,
                qtzc: 20,
            },
            {
                id: 17,
                date: "2021-06-05",
                lr: 1230,
                xse: 1500,
                xscb: 300,
                qtsr: 50,
                qtzc: 20,
            },
            {
                id: 18,
                date: "2021-06-06",
                lr: 282,
                xse: 512,
                xscb: 312,
                qtsr: 422,
                qtzc: 342,
            },
            {
                id: 19,
                date: "2021-06-07",
                lr: 2800,
                xse: 5100,
                xscb: 3100,
                qtsr: 4200,
                qtzc: 3400,
            },
            {
                id: 20,
                date: "2021-06-08",
                lr: 280,
                xse: 510,
                xscb: 310,
                qtsr: 420,
                qtzc: 340,
            },
            {
                id: 21,
                date: "2021-06-09",
                lr: 1230,
                xse: 1500,
                xscb: 300,
                qtsr: 50,
                qtzc: 20,
            },
            {
                id: 22,
                date: "2021-06-10",
                lr: 1600,
                xse: 3200,
                xscb: 1000,
                qtsr: 1600,
                qtzc: 2200,
            },
            {
                id: 23,
                date: "2021-06-11",
                lr: 1600,
                xse: 3279,
                xscb: 1069,
                qtsr: 1609,
                qtzc: 2219
            }
        ],
        booksList: [{
                id: 1,
                title: "有理想就有疼痛",
                pic: "http://api.jisuapi.com/isbn/upload/62/ff0e28ce5da3dd.jpg",
                author: "高晓春",
                summary: "《有理想就有疼痛:中国当代文化名人访谈录》是一份关于当代中国文化的最真实底稿，收录了高晓春与白先勇、冯骥才、余华、莫言、余秋雨、陈忠实等20位当代中国文化大家的对话。通过近距离的访谈，展现了这些文化大家多彩的内心世界，也阐释了他们对生命、艺术、财富及文化的理解。",
                publisher: "安徽人民出版社",
                stock: 3,
                pricein: 20.8,
                priceout: 28.8,
                isbn: 9787212058937,
                cate: 2,
            },
            {
                id: 2,
                title: "风的女儿",
                pic: "https://img1.doubanio.com/view/subject/l/public/s33859918.jpg",
                author: " (英) 克莱尔·马利 (Clare Mully)",
                summary: "本书是一部真实的双人传记，通过1936年奥运会、东方战线、柏林航空俱乐部等背景，讲述了二战时期两位德国女飞行员的真实人生往事。汉娜和梅利塔都战胜了舆论对女性的偏见，在20世纪30年代男性占主导地位的德国飞行领域争得了一席之地。然而，两人的命运截然不同，她们也不能苟同对方的抉择。出身中产阶级的汉娜是雅利安人，在1945年企图将希特勒带出柏林，失败后被世人所鄙弃；而不爱出风头的普鲁士贵族梅利塔，却全家支持并参与了最著名的元首刺杀计划：“女武神”行动，为此付出了血的代价。",
                publisher: "生活书店出版有限公司",
                stock: 4,
                pricein: 20.8,
                priceout: 28.8,
                isbn: 9787807683315,
                cate: 1,
            },
            {
                id: 3,
                title: "一切皆契约：真实世界中的博弈与决策",
                pic: "http://api.jisuapi.com/isbn//upload/e5/a9497cda03c508.jpg",
                author: "聂辉华",
                publisher: "上海三联书店",
                summary: "刚工作时该不该好好表现？ 为什么主观考核会产生“马屁精”？ KPI考核的弊端是什么？ 为什么组织内部不能随便引入竞争机制？ 什么样的家族企业能长盛不衰？ 为什么合同要故意留下漏洞？ 教师、医生应该有固定工资，还是绩效工资？ 企业管理人员的收入应当多少来自奖金，多少来自认股权？ 中央和地方如何分钱机制是不是影响了房价？ 现代社会契约无处不在，小到个人借贷的贷款合同，员工的雇佣合同，大至公司之间的合作协议，甚至是国家之间签订的贸易合作协议，这些都是契约的一种形式。",
                stock: 5,
                pricein: 20.8,
                priceout: 28.8,
                isbn: 9787212058937,
                cate: 2,
            },
            {
                id: 4,
                title: "红楼梦",
                pic: "http://api.jisuapi.com/isbn/upload/4a/fd1b2d49bb9ae9.jpg",
                author: "曹雪芹",
                summary: "《红楼梦》是一部百科全书式的长篇小说。以宝黛爱情悲剧为主线，以四大家族的荣辱兴衰为背景，描绘出18世纪中国封建社会的方方面面，以及封建专制下新兴资本主义民主思想的萌动。结构宏大、情节委婉、细节精致，人物形象栩栩如生，声口毕现，堪称中国古代小说中的经典。",
                publisher: "人民文学出版社",
                isbn: "9787020002207",
                stock: 2,
                pricein: 20.1,
                priceout: 30.8,
                cate: 1,
            },
            {
                id: 5,
                title: "活着",
                pic: "http://api.jisuapi.com/isbn/upload/25/9476640f9a8bd0.jpg",
                author: "余华",
                summary: "本书是长篇小说。",
                publisher: "作家出版社",
                isbn: "9787506365437",
                stock: 13,
                pricein: 20.1,
                priceout: 30.8,
                cate: 1,
            },
            {
                id: 6,
                title: "追风筝的人",
                pic: "http://api.jisuapi.com/isbn/upload/c7/a4ae03ddb978f9.jpg",
                author: "(美) 胡赛尼 (Hosseini,K.)",
                summary: "本书讲述的是：12岁的富家少爷阿米尔与仆人哈山情同手足，因为一场风筝比赛，两人的亲密友谊从此发生了改变。",
                publisher: "上海人民出版社",
                isbn: "9787208061644",
                stock: 2,
                pricein: 20.1,
                priceout: 30.8,
                cate: 1,
            },
            {
                id: 7,
                title: "许三观卖血记",
                pic: "http://api.jisuapi.com/isbn/upload/12/5f8e1e0ab9c5ee.jpg",
                author: "余华",
                summary: "《许三观卖血记》是余华1995年创作的一部长篇小说，它以博大的温情描绘了磨难中的人生，以激烈的故事形式表达了人在面对厄运时求生的欲望。小说讲述了许三观靠着卖血渡过了人生的一个个难关，战胜了命运强加给他的惊涛骇浪，而当他老了，知道自己的血再也没有人要时，精神却崩溃了。",
                publisher: "南海出版公司",
                isbn: "9787544211765",
                stock: 1,
                pricein: 20.1,
                priceout: 30.8,
                cate: 1,
            },
            {
                id: 8,
                title: "围城",
                pic: "http://api.jisuapi.com/isbn/upload/6e/ee08e326eb5db7.png",
                author: "钱锺书",
                summary: "《围城》是钱钟书所著的长篇小说。第一版于1947年由上海晨光出版公司出版。1949年之后，由于政治等方面的原因，本书长期无法在中国大陆和台湾重印，仅在香港出现过盗印本。1980年由作者重新修订之后，在中国大陆地区由人民文学出版社刊印。此后作者又曾小幅修改过几次。《围城》自从出版以来，就受到许多人的推重。由于1949年后长期无法重印，这本书逐渐淡出人们的视野。也有人认为这是作者卖弄文字，语言显得尖酸刻薄。但这一说法并不为大多数人接受。",
                publisher: "人民文学出版社",
                isbn: "9787020024759",
                stock: 6,
                pricein: 20.1,
                priceout: 30.8,
                cate: 1,
            },
            {
                id: 9,
                title: "白鹿原",
                pic: "http://api.jisuapi.com/isbn/upload/47/a09047bde4a207.jpg",
                author: "陈忠实",
                summary: "这是一部渭河平原五十年变迁的雄奇史诗，一轴中国农村班斓多彩、触目惊心的长幅画卷。主人公六娶六丧，神秘的序曲预示着不祥。一个家族两代子孙，为争夺白鹿原的统治代代争斗不已，上演了一幕幕惊心动魄的活剧：巧取风水地，恶施美人计，孝子为匪，亲翁杀媳，兄弟相煎，情人反目……大革命、日寇入侵、三年内战，白鹿原翻云覆雨，王旗变幻，家仇国恨交错缠结，冤冤相报代代不已……",
                publisher: "人民文学出版社",
                isbn: "9787020026906",
                stock: 8,
                pricein: 20.1,
                priceout: 30.8,
                cate: 3,
            },
            {
                id: 10,
                title: "骆驼祥子",
                pic: "http://api.jisuapi.com/isbn/upload/36/b412099f44e6f2.jpg",
                author: "老舍",
                summary: "《骆驼祥子》是老舍用同情的笔触描绘的一幕悲剧：二十年代的北京，一个勤劳、壮实的底层社会小人物怀着发家、奋斗的美好梦想，却最终为黑暗的暴风雨所吞噬。它揭示了当时“小人物”的奴隶心理和希望的最终破灭。随着祥子心爱的女人小福子的自杀，祥子熄灭了个人奋斗的最后一朵火花。这是旧中国老北京贫苦市民的典型命运。",
                publisher: "人民文学出版社",
                isbn: "9787020028115",
                stock: 5,
                pricein: 20.1,
                priceout: 30.8,
                cate: 3,
            },
            {
                id: 11,
                title: "城南旧事",
                pic: "http://api.jisuapi.com/isbn/upload/81/52557cea27f5c3.jpg",
                author: "林海音",
                summary: "本书描写了30年代北京城南的普通市民生活。",
                publisher: "中国青年出版社",
                isbn: "9787500652045",
                stock: 7,
                pricein: 20.1,
                priceout: 30.8,
                cate: 3,
            },
            {
                id: 12,
                title: "小王子",
                pic: "http://api.jisuapi.com/isbn/upload/44/767c85be1af667.jpg",
                author: "(法) 埃克苏佩里 (Exupery,S.)",
                summary: "本书是二十世纪流传最广的童话，从1943年发表以来，已译成一百多种文字。",
                publisher: "人民文学出版社",
                isbn: "9787020042494",
                stock: 9,
                pricein: 20.1,
                priceout: 30.8,
                cate: 3,
            },
            {
                id: 13,
                title: "百年孤独",
                pic: "http://api.jisuapi.com/isbn/upload/76/2d09c348edd829.jpg",
                author: " (哥伦) 马尔克斯 (Marquez,G.G.)",
                summary: "本书是哥伦比亚当代长篇小说。《百年孤独》是拉丁美洲魔幻现实主义文学流派的代表作，刻画了布恩迪亚家族七代人的传奇经历，描绘了加勒比海沿岸小镇马孔多的百年兴衰，成为20世纪最重要的经典文学巨著之一。",
                publisher: "南海出版公司",
                isbn: "9787544253994",
                stock: 4,
                pricein: 20.1,
                priceout: 30.8,
                cate: 3,
            },
            {
                id: 14,
                title: "老人与海",
                pic: "http://api.jisuapi.com/isbn/upload/bd/c99cf1e1a676e4.jpg",
                author: "海明威",
                summary: "本书讲述了一个渔夫的故事。古巴老渔夫圣地亚哥在连续八十四天没捕到鱼的情况下，终于独自钓上了一条大马林鱼，但这鱼实在大，把他的小船在海上拖了三天才筋疲力尽，被他杀死了绑在小船的一边。在归程中，他再遭到一条鲨鱼的袭击，最后回港时只剩鱼头鱼尾和一条脊骨。而在老圣地亚哥出海的日子里，他的忘年好友一直在海边忠诚地等待，满怀信心地迎接着他的归来。",
                publisher: "上海译文出版社",
                isbn: "9787532723447",
                stock: 9,
                pricein: 20.1,
                priceout: 30.8,
                cate: 3,
            },
            {
                id: 15,
                title: "了不起的盖茨比",
                pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                author: "(美) 菲茨杰拉德",
                summary: "军人盖茨比与富家小姐戴西在战争期间相爱，但因他当时贫穷，她选择了富人汤姆。战后盖茨比经商致富。他花天酒地，日夜设宴，以吸引戴西，最终通过经心安排与旧日情人旧梦重温。汤姆因妒忌利用一次车祸陷害了盖茨比，将他致于死地。",
                publisher: "人民文学出版社",
                isbn: "9787020046089",
                stock: 6,
                pricein: 20.1,
                priceout: 30.8,
                cate: 3,
            },
            {
                id: 16,
                title: "挪威的森林",
                pic: "http://api.jisuapi.com/isbn/upload/82/a18b4840594c98.jpg",
                author: "[日] 村上春树",
                summary: "这是一部动人心弦的、平缓舒雅的、略带感伤的恋爱小说。小说主人公渡边以第一人称展开他同两个女孩间的爱情纠葛。渡边的第一个恋人直子原是他高中要好同学木月的女友，后来木月自杀了。一年后渡边同直子不期而遇并开始交往。此时的直子已变得娴静腼腆，美丽晶莹的眸子里不时掠过一丝难以捕捉的阴翳。两人只是日复一日地在落叶飘零的东京街头漫无目标地或前或后或并肩行走不止。直子20岁生日的晚上两人发生了性关系，不料第二天直子便不知去向。",
                publisher: "上海译文出版社",
                isbn: "9787532725694",
                stock: 7,
                pricein: 20.1,
                priceout: 30.8,
                cate: 3,
            },
            {
                id: 17,
                title: "海边的卡夫卡",
                pic: "http://api.jisuapi.com/isbn/upload/69/a4f2d8f3a4f7e1.jpg",
                author: "(日) 村上春树",
                summary: "本书是作者最新的长篇小说。讲述一个15岁少年立志成为世界上最坚韧的人，离家踏上“不重复第二遍”的旅途，由此遇上一系列奇人奇事。",
                publisher: "上海译文出版社",
                isbn: "9787532734191",
                stock: 11,
                pricein: 20.1,
                priceout: 30.8,
                cate: 1,
            },
            {
                id: 18,
                title: "1Q84",
                pic: "http://api.jisuapi.com/isbn/upload/15/36098064f622c6.jpg",
                author: " (日) 村上春树",
                summary: "本书是日本当代长篇小说。本作品由二十四章组成，奇数章描绘心灵曾饱受创伤的年轻女子青豆的故事，偶数章则讲述笔耕不缀的数学教师天吾的经历。青豆在执行紧急任务的路途中，在首都高速公路陷入拥堵，她于是从紧急出口的楼梯走下，却进入一个与她彼时生活的1984年相似却不尽相同、有着微妙差异的1Q84年的世界。而天吾在改写谜一般的美少女作家深绘里的小说《空气蛹》的过程中，被卷入各种奇妙事态，此前知足常乐的平常心发生严重的倾斜。",
                publisher: "南海出版公司",
                isbn: "9787544247269",
                stock: 13,
                pricein: 20.1,
                priceout: 30.8,
                cate: 1,
            },
            {
                id: 19,
                title: "且听风吟",
                pic: "http://api.jisuapi.com/isbn/upload/dd/7e1a26844c8411.jpg",
                author: "[日] 村上春树",
                summary: "《且听风吟》是村上春树的成名作，他是以这部中篇开始文学创作的。\n小说的情节并不很复杂。“我”在酒吧喝酒，去卫生间时见一少女醉倒在地，遂就其护送回家，翌日少女发现自己一丝不挂，斥责“我”侮辱了她，“我”有口难辩。但几天后，两人逐渐亲密……不料“我”寒假回来，少女已无处可寻，只好一个人坐在原来两人坐过的地方怅怅地望着大海。",
                publisher: "上海译文出版社",
                isbn: "9787532726172",
                stock: 3,
                pricein: 20.1,
                priceout: 30.8,
                cate: 1,
            },
            {
                id: 20,
                title: "乡下人：沈从文与近代中国",
                author: "孙德鹏",
                publisher: "广西师范大学出版社",
                pic: "http://api.jisuapi.com/isbn//upload/d6/6648068a0efbbc.jpg",
                summary: "这是一部沈从文评传，也是作者与沈从文之间的一次跨学科对话。作者以史学为点，从 “乡下人”的视角回顾沈从文的前半生，在沈从文作品中重建近代中国的记忆，从湘西叙事找寻理解近代中国的另一种方法。 不同于一般从生平出发的人物立传，作者立足沈从文自称“乡下人”的人生经验，结合法史哲等多学科思想、小说文本对其经历与情感展开的推演想象，使得小说人物与传主形象交相辉映，实现了文学对历史的叙事性补充。并通过城市与乡村之间的对照，展现了近代中国的一些独特面向。",
                isbn: "9787559837097",
                stock: 1,
                pricein: 40.0,
                priceout: 88.0,
                cate: 13,
            },
        ],
        booksnum: 20,
        goodList: [{
                id: 1,
                pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i2/170060037/O1CN01U2NuPZ1C8zI4R3ieo_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                name: "铅笔",
                pricein: 1,
                priceout: 2,
                num: 500,
                cate: 1,
            },
            {
                id: 2,
                pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/98749545/O1CN01IeOtHZ2KNf1BuBl5D_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                name: "钢笔",
                pricein: 5,
                priceout: 10,
                num: 50,
                cate: 1,
            },
            {
                id: 3,
                pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                name: "笔记本",
                pricein: 5,
                priceout: 10,
                num: 50,
                cate: 1,
            },
            {
                id: 4,
                pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i2/725677994/O1CN01wDVLzm28vIph7yn2Z_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                name: "可口可乐",
                pricein: 2,
                priceout: 5,
                num: 100,
                cate: 2,
            },
            {
                id: 5,
                pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                name: "百事可乐",
                pricein: 2,
                priceout: 5,
                num: 100,
                cate: 2,
            },
            {
                id: 6,
                pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/i1/2530652864/O1CN01BgZnlF1X1l0WgobzE_!!2530652864.jpg_580x580Q90.jpg_.webp",
                name: "卡布奇诺",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 2,
            },
            {
                id: 7,
                pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i2/2378827303/O1CN01WdrWuG23op81S3bdx_!!2378827303.jpg_580x580Q90.jpg_.webp",
                name: "红豆奶茶",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 2,
            },
            {
                id: 8,
                pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/i1/2617739568/O1CN01VVzJiC2KYCCg738MD_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                name: "豆乳盒子",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 3,
            },
            {
                id: 9,
                pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/i1/2455221099/O1CN01iYTxji1JzNvjWpFVD_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                name: "红丝绒蛋糕",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 3,
            },
            {
                id: 10,
                pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i1/692220097/O1CN01E7w5h61CaT3VEmGHv_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                name: "马卡龙",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 3,
            },
            {
                id: 11,
                pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/619123122/O1CN01X8dgFY1YvvCdXi7Dl_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                name: "华夫饼",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 3,
            },
            {
                id: 12,
                pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/i1/2208061596517/O1CN01UxYCsc1y0ppLAUwT2_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                name: "钥匙扣",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 4,
            },
            {
                id: 13,
                pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i1/2201402902040/O1CN016DQM9V1QwMdxk728p_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                name: "书签",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 4,
            },
            {
                id: 14,
                pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/49723483/O1CN018qnYwd1bbG7LWuZq2_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                name: "海报",
                pricein: 12,
                priceout: 25,
                num: 100,
                cate: 4,
            },

        ],
        goodscateList: [{
                id: 1,
                name: '文具',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            },
            {
                id: 2,
                name: '饮料',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            },
            {
                id: 3,
                name: '小食',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            },
            {
                id: 4,
                name: '小商品',
                pics: 'https://www.hualigs.cn/image/60b367e803d9c.jpg',
            }
        ],
        assistantList: [{
                id: 0,
                name: "曾智",
                post: 1,
                phonenum: 18800416241,
                gender: 1,
                day: "2021-01-01",
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
            },
            {
                id: 1,
                name: "AA",
                post: 2,
                phonenum: 18800416241,
                gender: 1,
                day: "2021-01-01",
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
            },
            {
                id: 2,
                name: "BB",
                post: 3,
                phonenum: 18800416241,
                gender: 0,
                day: "2021-01-01",
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
            },
            {
                id: 3,
                name: "CC",
                post: 4,
                phonenum: 18800416241,
                gender: 1,
                day: "2021-01-01",
                pics: 'https://www.hualigs.cn/image/60be3bb79f39d.jpg',
            },
        ],
        postList: [{
                id: 1,
                name: "管理员"
            },
            {
                id: 2,
                name: "店长"
            },
            {
                id: 3,
                name: "店员"
            },
            {
                id: 4,
                name: "厨师"
            },
        ],
        feedback: [{
                id: 2,
                date: "2021-06-02",
                content: "在家闲着太无聊出来逛街，家里小学霸让我给她带书，书店统一的装修风格，还蛮喜欢的，工作人员服务也很好",
                customer: "徐洪磊",
            },
            {
                id: 7,
                date: "2021-06-07",
                content: "这是家装修很有风格很适合拍照的书店，而且书的种类很全，一进门基本涵盖了当前畅销的大部分小说",
                customer: "小a",
            },
            {
                id: 8,
                date: "2021-06-08",
                content: "环境真的是太好了！工作日咖啡店的位置还是很多的，但周末就会一座难求，甚至有一些学生会在那里点上一个饮品，学习一整天",
                customer: "赵梓良",
            },
            {
                id: 1,
                date: "2021-06-01",
                content: "很好，环境有书香气",
                customer: "赵梓良",
            },
            {
                id: 9,
                date: "2021-06-10",
                content: "年度最爱书店。店面环境优雅，具有人文温度。装修风格很喜欢。选书比较对本人“胃口”。",
                customer: "大大智",
            },
            {
                id: 11,
                date: "2021-06-10",
                content: "装修是英伦风格，除了买书以外还会卖一些小摆件，也有东西可以喝。",
                customer: "大智",
            },
            {
                id: 10,
                date: "2021-06-10",
                content: "书店与咖啡的结合，或许可以有很多思想的火花迸发",
                customer: "小小智",
            },
            {
                id: 5,
                date: "2021-06-05",
                content: "对于喜欢看书，又有点小资情调的朋友来说，去看书算得上是不错的选择",
                customer: "小智",
            },
            {
                id: 6,
                date: "2021-06-05",
                content: "为了打发时间走进久违的书店。 咖啡屋里面的座位基本都坐满了",
                customer: "赵梓良",
            },
            {
                id: 4,
                date: "2021-06-03",
                content: "这几天读书节，还在一楼有活动位置，满50送50卷很不错。",
                customer: "高昊达",
            },
            {
                id: 3,
                date: "2021-06-03",
                content: "喜欢收集书店的图章，所以每到一个书店都会选一本书盖上章做收藏。",
                customer: "郑君烨",
            },
        ],
        borrowList: [{
                id: 1000011,
                date: "2021-06-11",
                state: 0,
                customer: "高昊达",
                assistant: "曾智",
                msg: [{
                        id: 20,
                        title: "乡下人：沈从文与近代中国（1902—1947）",
                        pic: "http://api.jisuapi.com/isbn//upload/d6/6648068a0efbbc.jpg",
                        num: 1,
                    },
                    {
                        id: 1,
                        title: "有理想就有疼痛",
                        pic: "http://api.jisuapi.com/isbn/upload/62/ff0e28ce5da3dd.jpg",
                        num: 1,
                    },
                    {
                        id: 19,
                        title: "且听风吟",
                        pic: "http://api.jisuapi.com/isbn/upload/dd/7e1a26844c8411.jpg",
                        num: 1,
                    },
                    {
                        id: 17,
                        title: "海边的卡夫卡",
                        pic: "http://api.jisuapi.com/isbn/upload/69/a4f2d8f3a4f7e1.jpg",
                        num: 1,
                    },
                    {
                        id: 15,
                        title: "了不起的盖茨比",
                        pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                        num: 1,
                    },
                ]
            },
            {
                id: 1000010,
                date: "2021-06-11",
                state: 0,
                customer: "小智",
                assistant: "曾智",
                msg: [{
                        id: 20,
                        title: "乡下人：沈从文与近代中国（1902—1947）",
                        pic: "http://api.jisuapi.com/isbn//upload/d6/6648068a0efbbc.jpg",
                        num: 1,
                    },
                    {
                        id: 17,
                        title: "海边的卡夫卡",
                        pic: "http://api.jisuapi.com/isbn/upload/69/a4f2d8f3a4f7e1.jpg",
                        num: 1,
                    },
                    {
                        id: 15,
                        title: "了不起的盖茨比",
                        pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                        num: 1,
                    },
                ]
            },
            {
                id: 1000001,
                date: "2021-06-01",
                state: 1,
                customer: "小a",
                assistant: "曾智",
                msg: [{
                        pic: "http://api.jisuapi.com/isbn/upload/4a/fd1b2d49bb9ae9.jpg",
                        name: "红楼梦",
                        num: 1,
                    },
                    {
                        id: 1,
                        title: "有理想就有疼痛",
                        pic: "http://api.jisuapi.com/isbn/upload/62/ff0e28ce5da3dd.jpg",
                        num: 1,
                    },
                    {
                        id: 15,
                        title: "了不起的盖茨比",
                        pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                        num: 1,
                    },

                ]
            },
            {
                id: 1000002,
                date: "2021-06-02",
                state: 1,
                customer: "高昊达",
                assistant: "曾智",
                msg: [{
                        pic: "http://api.jisuapi.com/isbn/upload/4a/fd1b2d49bb9ae9.jpg",
                        name: "红楼梦",
                        num: 1,
                    },
                    {
                        id: 15,
                        title: "了不起的盖茨比",
                        pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                        num: 1,
                    }, {
                        id: 20,
                        title: "乡下人：沈从文与近代中国（1902—1947）",
                        pic: "http://api.jisuapi.com/isbn//upload/d6/6648068a0efbbc.jpg",
                        num: 1,
                    },
                ]
            },
            {
                id: 1000003,
                date: "2021-06-02",
                state: 1,
                customer: "赵梓良",
                assistant: "曾智",
                msg: [{
                    id: 1,
                    title: "有理想就有疼痛",
                    pic: "http://api.jisuapi.com/isbn/upload/62/ff0e28ce5da3dd.jpg",
                    num: 1,
                }, {
                    id: 20,
                    title: "乡下人：沈从文与近代中国（1902—1947）",
                    pic: "http://api.jisuapi.com/isbn//upload/d6/6648068a0efbbc.jpg",
                    num: 1,
                }, ]
            },
            {
                id: 1000004,
                date: "2021-06-02",
                state: 1,
                customer: "小b",
                assistant: "曾智",
                msg: [{
                        id: 1,
                        title: "有理想就有疼痛",
                        pic: "http://api.jisuapi.com/isbn/upload/62/ff0e28ce5da3dd.jpg",
                        num: 1,
                    },
                    {
                        id: 15,
                        title: "了不起的盖茨比",
                        pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                        num: 1,
                    },
                ]
            },
            {
                id: 1000005,
                date: "2021-06-05",
                state: 1,
                customer: "小a",
                assistant: "曾智",
                msg: [{
                        pic: "http://api.jisuapi.com/isbn/upload/4a/fd1b2d49bb9ae9.jpg",
                        name: "红楼梦",
                        num: 1,
                    },
                    {
                        id: 15,
                        title: "了不起的盖茨比",
                        pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                        num: 1,
                    },
                ]
            },
            {
                id: 1000006,
                date: "2021-06-06",
                state: 1,
                customer: "小小智",
                assistant: "曾智",
                msg: [{
                    id: 15,
                    title: "了不起的盖茨比",
                    pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                    num: 1,
                }, ]
            },
            {
                id: 1000007,
                date: "2021-06-07",
                state: 1,
                customer: "大智",
                assistant: "曾智",
                msg: [{
                    pic: "http://api.jisuapi.com/isbn/upload/4a/fd1b2d49bb9ae9.jpg",
                    name: "红楼梦",
                    num: 1,
                }, {
                    id: 20,
                    title: "乡下人：沈从文与近代中国（1902—1947）",
                    pic: "http://api.jisuapi.com/isbn//upload/d6/6648068a0efbbc.jpg",
                    num: 1,
                }, ]
            },
            {
                id: 1000008,
                date: "2021-06-08",
                state: 1,
                customer: "郑君烨",
                assistant: "曾智",
                msg: [{
                    pic: "http://api.jisuapi.com/isbn/upload/4a/fd1b2d49bb9ae9.jpg",
                    name: "红楼梦",
                    num: 1,
                }, {
                    id: 20,
                    title: "乡下人：沈从文与近代中国（1902—1947）",
                    pic: "http://api.jisuapi.com/isbn//upload/d6/6648068a0efbbc.jpg",
                    num: 1,
                }, ]
            },
            {
                id: 1000009,
                date: "2021-06-11",
                state: 0,
                customer: "高昊达",
                assistant: "曾智",
                msg: [{
                    id: 15,
                    title: "了不起的盖茨比",
                    pic: "http://api.jisuapi.com/isbn/upload/fd/3dc7d178e20431.jpg",
                    num: 1,
                }, {
                    id: 20,
                    title: "乡下人：沈从文与近代中国（1902—1947）",
                    pic: "http://api.jisuapi.com/isbn//upload/d6/6648068a0efbbc.jpg",
                    num: 1,
                }, ]
            },
        ],
        sellList: [{
                id: 1000011,
                date: "2021-06-11",
                state: 0,
                customer: "高昊达",
                assistant: "曾智",
                price: 46,
                msg: [{
                    id: 1,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i2/170060037/O1CN01U2NuPZ1C8zI4R3ieo_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "铅笔",
                    num: 3,
                }, {
                    id: 14,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/49723483/O1CN018qnYwd1bbG7LWuZq2_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "海报",
                    num: 1,
                }, {
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, ]
            },
            {
                id: 1000010,
                date: "2021-06-11",
                state: 0,
                customer: "小智",
                assistant: "曾智",
                price: 100,
                msg: [{
                    id: 1,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i2/170060037/O1CN01U2NuPZ1C8zI4R3ieo_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "铅笔",
                    num: 5,
                }, {
                    id: 14,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/49723483/O1CN018qnYwd1bbG7LWuZq2_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "海报",
                    num: 1,
                }, {
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, {
                    id: 3,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "笔记本",
                    num: 5,
                }, ]
            },
            {
                id: 1000012,
                date: "2021-06-11",
                state: 0,
                customer: "小智",
                assistant: "曾智",
                price: 120,
                msg: [{
                    id: 1,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i2/170060037/O1CN01U2NuPZ1C8zI4R3ieo_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "铅笔",
                    num: 5,
                }, {
                    id: 14,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/49723483/O1CN018qnYwd1bbG7LWuZq2_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "海报",
                    num: 1,
                }, {
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, {
                    id: 3,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "笔记本",
                    num: 5,
                }, ]
            },
            {
                id: 1000001,
                date: "2021-06-01",
                state: 1,
                customer: "小a",
                assistant: "曾智",
                price: 50,
                msg: [{
                        id: 14,
                        pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/49723483/O1CN018qnYwd1bbG7LWuZq2_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                        name: "海报",
                        num: 1,
                    },
                    {
                        id: 5,
                        pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                        name: "百事可乐",
                        num: 1,
                    }, {
                        id: 3,
                        pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                        name: "笔记本",
                        num: 1,
                    },
                ]
            },
            {
                id: 1000002,
                date: "2021-06-02",
                state: 1,
                customer: "高昊达",
                assistant: "曾智",
                price: 45,
                msg: [{
                    id: 14,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/49723483/O1CN018qnYwd1bbG7LWuZq2_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "海报",
                    num: 1,
                }, {
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, ]
            },
            {
                id: 1000003,
                date: "2021-06-02",
                state: 1,
                customer: "赵梓良",
                assistant: "曾智",
                price: 45,
                msg: [{
                    id: 14,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/49723483/O1CN018qnYwd1bbG7LWuZq2_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "海报",
                    num: 1,
                }, {
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, ]
            },
            {
                id: 1000004,
                date: "2021-06-02",
                state: 1,
                customer: "小b",
                assistant: "曾智",
                price: 100,
                msg: [{
                    id: 10,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i1/692220097/O1CN01E7w5h61CaT3VEmGHv_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "马卡龙",
                    num: 5,
                }, {
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, {
                    id: 14,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i4/49723483/O1CN018qnYwd1bbG7LWuZq2_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "海报",
                    num: 1,
                }, ]
            },
            {
                id: 1000005,
                date: "2021-06-05",
                state: 1,
                customer: "小a",
                assistant: "曾智",
                price: 25,
                msg: [{
                    id: 10,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i1/692220097/O1CN01E7w5h61CaT3VEmGHv_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "马卡龙",
                    num: 1,
                }, {
                    id: 3,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "笔记本",
                    num: 1,
                }, ]
            },
            {
                id: 1000006,
                date: "2021-06-06",
                state: 1,
                customer: "小小智",
                assistant: "曾智",
                price: 60,
                msg: [{
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, {
                    id: 3,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "笔记本",
                    num: 1,
                }, {
                    id: 10,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i1/692220097/O1CN01E7w5h61CaT3VEmGHv_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "马卡龙",
                    num: 1,
                }, ]
            },
            {
                id: 1000007,
                date: "2021-06-07",
                state: 1,
                customer: "大智",
                assistant: "曾智",
                price: 240,
                msg: [{
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, {
                    id: 3,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "笔记本",
                    num: 5,
                }, {
                    id: 10,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i1/692220097/O1CN01E7w5h61CaT3VEmGHv_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "马卡龙",
                    num: 5,
                }, ]
            },
            {
                id: 1000008,
                date: "2021-06-11",
                state: 0,
                customer: "郑君烨",
                assistant: "曾智",
                price: 40,
                msg: [{
                    id: 3,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "笔记本",
                    num: 5,
                }, ]
            },
            {
                id: 1000009,
                date: "2021-06-11",
                state: 0,
                customer: "高昊达",
                assistant: "曾智",
                price: 140,
                msg: [{
                    id: 3,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i4/2138614417/O1CN01GOrHyM1iV24V5Jb9E_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "笔记本",
                    num: 1,
                }, {
                    id: 10,
                    pic: "https://g-search1.alicdn.com/img/bao/uploaded/i4/imgextra/i1/692220097/O1CN01E7w5h61CaT3VEmGHv_!!0-saturn_solar.jpg_580x580Q90.jpg_.webp",
                    name: "马卡龙",
                    num: 5,
                }, {
                    id: 5,
                    pic: "https://g-search3.alicdn.com/img/bao/uploaded/i4/i3/725677994/O1CN01GghLvP28vIpdarzmB_!!0-item_pic.jpg_580x580Q90.jpg_.webp",
                    name: "百事可乐",
                    num: 1,
                }, ]
            },
        ],
        outList:[
            {
                id: 1001,
                date: "2021-05-31",
                price:250.8,
                reason:"5月电费"
        },
            {
                id: 1002,
                date: "2021-05-31",
                price:53.1,
                reason:"5月水费"
        },
            {
                id: 1003,
                date: "2021-06-03",
                price:1500,
                reason:"广告费"
        },
            {
                id: 1004,
                date: "2021-06-03",
                price:500,
                reason:"发传单"
        },
            {
                id: 1005,
                date: "2021-06-04",
                price:100,
                reason:"做活动条幅"
        },
        ],
        inList:[
            {
                id: 1001,
                date: "2021-05-21",
                price:190,
                reason:"顾客现金支付购买图书"
        },
            {
                id: 1002,
                date: "2021-05-31",
                price:2594.6,
                reason:"5月其他收入"
        },
            {
                id: 1003,
                date: "2021-06-03",
                price:500,
                reason:"广告商退款"
        },
            {
                id: 1004,
                date: "2021-06-06",
                price:1500,
                reason:"加盟店分红广告费"
        },
            {
                id: 1005,
                date: "2021-06-10",
                price:1500,
                reason:"承办读书沙龙"
        },
        ],
        newsellnum:5,
        newborrownum:3,

    },
    onLaunch: function(options) {

    },
    onShow: function(options) {

    },
    onHide: function() {

    },
    onError: function(msg) {

    },
    //options(path,query,isEntryPage)
    onPageNotFound: function(options) {

    }
});